apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers: 
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: yourpassword
          ports: 
            - containerPort: 3306
              name: mysql
          volumeMounts:
              # name must match the volume name below
            - name: mysql-persistent-storage
              # mount path within the container
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: 600Mi
              cpu: 100m
      volumes:
        - name: mysql-persistent-storage
          gcePersistentDisk:
            # This GCE PD must already exist.
            pdName: mysql-disk-prod
            fsType: ext4
