apiVersion: skaffold/v1beta9
kind: Config
profiles:
  # This is the profile for staging.
  - name: staging
    build:
      artifacts:
       - image: asia.gcr.io/ianlewis-org/homepage
         context: "."
    deploy:
      kustomize:
        path: ./kubernetes/staging

  # This is the profile for production.
  - name: prod
    build:
      artifacts:
       - image: asia.gcr.io/ianlewis-org/homepage
         context: "."
    deploy:
      kustomize:
        path: ./kubernetes/prod

  # Profile for migration for staging
  - name: migrate_staging
    build:
      artifacts:
        - image: asia.gcr.io/ianlewis-org/homepage
          context: "."
    deploy:
      kustomize:
        path: ./kubernetes/extras/migrate/staging

  # Profile for migration for staging
  - name: migrate_prod
    build:
      artifacts:
        - image: asia.gcr.io/ianlewis-org/homepage
          context: "."
    deploy:
      kustomize:
        path: ./kubernetes/extras/migrate/prod
