apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: homepage-backup
spec: 
  selector:
    matchLabels:
      name: homepage-backup
      version: v8
  template:
    metadata:
      name: homepage-backup
      labels:
        name: homepage-backup
        version: v8
    spec:
      containers: 
        - image: asia.gcr.io/ianlewis-org/homepage-backup:v8
          name: homepage-backup
          env:
            - name: BOTO_CONFIG
              value: '/etc/secrets/gsutil-config'
          volumeMounts:
            - name: secret-volume
              mountPath: '/etc/secrets'
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
      volumes:
        - name: secret-volume
          secret:
            secretName: homepage-backup-secret
      restartPolicy: Never
