apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: backup-job-name-placeholder
spec:
  selector:
    matchLabels:
      name: backup-job-name-placeholder
      version: v9
  template:
    metadata:
      name: backup-job-name-placeholder
      labels:
        name: backup-job-name-placeholder
        version: v9
    spec:
      containers:
        - image: asia.gcr.io/ianlewis-org/homepage-backup:v9
          name: homepage-backup
          env:
            - name: BOTO_CONFIG
              value: '/etc/secrets/gsutil-config'
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  name: backup-conf
                  key: bucket.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: secret-volume
              mountPath: '/etc/secrets'
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
      volumes:
        - name: secret-volume
          secret:
            secretName: homepage-backup-secret
      restartPolicy: Never
