kind: ConfigMap
apiVersion: v1
metadata:
  name: renew-certs-config
  namespace: homepage-prod
data:
  gce-project: ianlewis-org 
  email: ianmlewis@gmail.com
  zone: ianlewis-org
  domains: www.ianlewis.org api.ianlewis.org
