steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-w', '/homepage', 'python:2.7.13', 'build.sh']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/homepage:$TAG_NAME', '.']
  dir: 'subdirectory'
images: ['asia.gcr.io/$PROJECT_ID/homepage:$TAG_NAME']
