steps:
- name: 'python:2.7.13'
  args: ['bash', '-c', 'cd ./homepage && ./build.sh']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/homepage:$TAG_NAME', '.']
  dir: 'homepage'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deploy.yaml', '-n', 'staging']
  dir: 'homepage'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=asia-northeast1-ianlewis-org'
images: ['asia.gcr.io/$PROJECT_ID/homepage:$TAG_NAME']
