apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homepage
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 10%
  template:
    metadata:
      labels:
        name: homepage
    spec:
      containers:
        - name: homepage
          image: asia.gcr.io/ianlewis-org/homepage:0.2.3
          # defines the health checking
          livenessProbe:
            # an http probe
            httpGet:
              path: /_status/healthz
              port: 8080
            # length of time to wait for a pod to initialize
            # after pod startup, before applying health checking
            initialDelaySeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            # an http probe
            httpGet:
              path: /_status/readiness
              port: 8080
            # length of time to wait for a pod to initialize
            # after pod startup, before applying health checking
            initialDelaySeconds: 15
            timeoutSeconds: 1
          env:
            - name: DEBUG
              value: 'False'
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-secret
                  key: secret-key
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: homepage-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homepage-secret
                  key: db-password
            - name: DISQUS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-secret
                  key: disqus-api-key
            - name: DISQUS_WEBSITE_SHORTNAME
              valueFrom:
                secretKeyRef:
                  name: homepage-secret
                  key: disqus-website-shortname
            - name: MEDIA_ROOT
              value: /var/www/media
            - name: USE_MEMCACHED
              value: 'False'
            - name: MEMCACHED_HOSTS
              value: memcached:11211
            - name: HTTPS
              value: "on"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 150Mi
              cpu: 50m
        - name: nginx
          image: asia.gcr.io/ianlewis-org/nginx:1.11.1-3
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 10Mi
              cpu: 10m 
