apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: homepage-migrate
spec:
  selector:
    matchLabels:
      name: homepage-migrate
  template:
    metadata:
      name: hompage-migrate
      labels:
        name: homepage-migrate
    spec:
      containers:
        - name: homepage-migrate
          image: asia.gcr.io/ianlewis-org/homepage:0.3.6
          command: ["homepage", "migrate"]
          env:
            - name: DEBUG
              value: 'False'
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-secret
                  key: secret-key
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: homepage-secret
                  key: db-admin-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homepage-secret
                  key: db-admin-password
            - name: MEDIA_ROOT
              value: /var/www/media
            - name: USE_MEMCACHED
              value: 'False'
            - name: MEMCACHED_HOSTS
              value: memcached:11211
            - name: ENV_DIR
              value: /etc/secrets
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
      restartPolicy: Never
