apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: homepage
    version: "3"
  name: homepage-v3
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: http2
      port: 443
      targetPort: 8001
  selector: 
    name: homepage
  type: NodePort
