apiVersion: "alpha.ianlewis.org/v1"
kind: "CronTab"
metadata:
  name: hello-world
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    containers:
      - name: hello-world
        image: hello-world
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
    restartPolicy: Never
