apiVersion: v1beta3
kind: Service
metadata: 
  labels: 
    name: homepage
  name: homepage
spec: 
  ports:
    - port: 80
      targetPort: 8000
  selector: 
    name: homepage
  createExternalLoadBalancer: true
