apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: homepage
    version: "1"
  name: homepage-v3
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: http2
      port: 443
      targetPort: 3000
  selector: 
    name: homepage
  type: LoadBalancer
