apiVersion: v1
kind: ReplicationController
metadata:
  name: homepage-0.1.19-0
  labels:
    name: homepage
    version: 0.1.19-0
spec:
  replicas: 2
  selector:
    name: homepage
    version: 0.1.19-0
  template:
    metadata:
      labels:
        name: homepage
        version: 0.1.19-0
    spec:
      containers:
        - name: homepage
          image: asia.gcr.io/ianlewis-org/homepage:0.1.19
          # defines the health checking
          livenessProbe:
            # an http probe
            httpGet:
              path: /_status/healthz
              port: 8080
            # length of time to wait for a pod to initialize
            # after pod startup, before applying health checking
            initialDelaySeconds: 30
            timeoutSeconds: 1
          env:
            - name: DEBUG
              value: 'False'
            - name: DB_HOST
              value: mysql
            - name: MEDIA_ROOT
              value: /var/www/media
            - name: USE_MEMCACHED
              value: 'False'
            - name: MEMCACHED_HOSTS
              value: memcached:11211
            - name: HTTPS
              value: "on"
            - name: ENV_DIR
              value: /etc/secrets
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
        - name: webfront
          image: asia.gcr.io/ianlewis-org/webfront:1.0.3
          ports:
            - containerPort: 8000
            - containerPort: 8001
          volumeMounts:
            - name: webfront-secrets
              mountPath: /conf
      volumes: 
        - name: secret-volume
          secret:
            secretName: homepage-secret
        - name: webfront-secrets
          secret:
            secretName: webfront-secret  
