apiVersion: v1
kind: ReplicationController
metadata:
  name: homepage-0.1.18-27
  labels:
    name: homepage
    version: 0.1.18-27
spec:
  replicas: 1
  selector:
    name: homepage
    version: 0.1.18-27
  template:
    metadata:
      labels:
        name: homepage
        version: 0.1.18-27
    spec:
      containers:
        - name: homepage
          image: asia.gcr.io/ianlewis-org/homepage:0.1.18
          env:
            - name: DEBUG
              value: 'False'
            - name: DB_HOST
              value: mysql
            - name: MEDIA_ROOT
              value: /var/www/media
            - name: USE_MEMCACHED
              value: 'False'
            - name: MEMCACHED_HOSTS
              value: memcached:11211
            - name: HTTPS
              value: "on"
            - name: ENV_DIR
              value: /etc/secrets
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
        # nginx with mod_pagespeed
        # nginx handles HTTP requests directly and redirects them to HTTPS
        - name: nginx 
          image: asia.gcr.io/ianlewis-org/nginx:1.9.5-pagespeed-1.9.32.10-33
          ports:
            - containerPort: 8000
            - containerPort: 8002
          volumeMounts:
            - name: ngx-pagespeed-cache
              mountPath: /var/ngx_pagespeed_cache
        # nghttpx handles HTTPS(HTTP/2) traffic only and forwards it
        # to nginx.
        - name: nghttpx
          image: asia.gcr.io/ianlewis-org/nghttpx:1.3.4-6
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: webfront-secrets
              mountPath: /conf
      volumes: 
        - name: secret-volume
          secret:
            secretName: homepage-secret
        - name: webfront-secrets
          secret:
            secretName: webfront-secret
        - name: ngx-pagespeed-cache
          emptyDir: {}
