apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: homepage
    version: "1"
  name: homepage-v1
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector: 
    name: homepage
  type: LoadBalancer
