apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twilio-forwarder
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 10%
  template:
    metadata:
      labels:
        name: twilio-forwarder
    spec:
      containers:
        - name: twilio-forwarder
          image: asia.gcr.io/ianlewis-org/twilio-forwarder:0.91
          env:
            - name: FIREBASE_URI_PATH
              value: /etc/twilio-forwarder/firebase-uri
            - name: FIREBASE_SECRET_PATH
              value: /etc/twilio-forwarder/firebase-secret
          # defines the health checking
          livenessProbe:
            # an http probe
            httpGet:
              path: /_status/healthz
              port: 8080
          readinessProbe:
            # an http probe
            httpGet:
              path: /_status/readiness
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 60
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: secret-volume
              mountPath: /etc/twilio-forwarder
          resources:
            limits:
              memory: 20Mi
              cpu: 50m
      volumes: 
        - name: certs
          hostPath:
            path: /etc/ssl/certs
        - name: secret-volume
          secret:
            secretName: twilio-forwarder-secret
