namespace: staging
secretGenerator:
- name: homepage-admin-secret
  files:
    - .secrets/admin-password
  literals:
    - admin-user=homepage-admin
  type: Opaque
- name: homepage-db-secret
  files:
    - .secrets/db-password
  literals:
    - db-user=homepage
  type: Opaque
- name: homepage-secret
  files:
    - .secrets/secret-key
  type: Opaque
