---

  - name: install memcached
    sudo: True
    action: apt name=memcached

  - name: write memcached.conf
    action: template src=memcached.conf.j2 dest=/etc/memcached.conf mode=0644
    sudo: True
    notify:
      - restart memcached
