kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: camlistore-blobs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      type: camlistore-blobs
