apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: camlistored
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: camlistored
      annotations:
        # Restrict scheduling to zone where volume is located.
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "failure-domain.beta.kubernetes.io/zone",
                        "operator": "In",
                        "values": ["asia-northeast1-c"]
                      }
                    ]
                  }
                ]
              }
            }
          }
    spec:
      containers: 
        - name: camlistore-nginx
          image: nginx:1.11.1-alpine
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx
            - name: nginx-secrets
              mountPath: /secret
          resources:
            requests:
              memory: 10Mi
              cpu: 50m
            limits:
              memory: 10Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 1
        - name: camlistored
          image: asia.gcr.io/ianlewis-org/camlistored:9e34d14ef5-1
          args:
            - "-configfile=/conf/server-config.json"
          ports: 
            - containerPort: 3179
              name: camlistored
          volumeMounts:
            - name: camlistore-blobs
              mountPath: /blobs
            - name: camlistore-index
              mountPath: /index
            - name: camlistore-server-config
              mountPath: /conf
            - name: camlistore-keyring
              mountPath: /keyring
          livenessProbe:
            httpGet:
              path: /ui/
              port: 3179
            initialDelaySeconds: 60
            timeoutSeconds: 1
          resources:
            requests:
              memory: 6000Mi
              cpu: 1
            limits:
              memory: 8500Mi
              cpu: 2
      volumes:
        - name: camlistore-blobs
          persistentVolumeClaim:
            claimName: camlistore-blobs
        - name: camlistore-index
          persistentVolumeClaim:
            claimName: camlistore-index
        - name: camlistore-server-config
          configMap:
            name: camlistore-server-config
        - name: camlistore-keyring
          secret:
            secretName: camlistore-keyring
        - name: nginx-conf
          configMap:
            name: camlistore-nginx-conf
        - name: nginx-secrets
          secret:
            secretName: camlistore-nginx
