apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: camlistored
  name: camlistored
spec: 
  ports:
    - name: https
      port: 443
      targetPort: 3179
  selector: 
    name: camlistored
  type: LoadBalancer
