apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: camlistored
  name: camlistored
spec: 
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector: 
    name: camlistored
  type: NodePort
