apiVersion: v1
kind: Service
metadata: 
  name: dyndns-server
  labels: 
    name: dyndns-server
    version: "1"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector: 
    name: dyndns-server
  type: NodePort
