kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      type: mysql-data
