apiVersion: v1
kind: PersistentVolume
metadata:
  name: GCE_PD_NAME
  labels:
    type: mysql-data
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    # This GCE PD must already exist.
    pdName: GCE_PD_NAME
    fsType: ext4
