- apt: update_cache=yes
  sudo: True

- name: Install packages required by app server
  action: apt pkg={{ item }} state=present
  sudo: True
  with_items:
    - python
    - python-dev
    - python-pip
    - python-virtualenv
    - mercurial
    - git
    - subversion
    - libmysqlclient-dev
    - libmemcached-dev
    - libjpeg-dev
    - zlib1g-dev

- name: Install environment
  sudo: True
  template: src=environment.sh.j2 dest=/etc/profile.d/environment.sh

- name: Create supervisord group
  sudo: True
  group: name={{supervisord_group}} state=present

- name: Create supervisord user
  sudo: True
  user: name={{supervisord_user}} group={{supervisord_group}} state=present

- name: Create media directory
  sudo: True
  file: path=/var/www/media owner={{supervisord_user}} group={{supervisord_group}} state=directory

- name: Create /var/run/homepage directory
  sudo: True
  file: path=/var/run/homepage owner={{supervisord_user}} group={{supervisord_group}} state=directory

- name: Create /var/log/homepage directory
  sudo: True
  file: path=/var/log/homepage owner={{supervisord_user}} group={{supervisord_group}} state=directory

- name: Install supervisor
  sudo: True
  shell: pip install supervisor==3.1.3

- name: Create /var/log/supervisor directory
  sudo: True
  file: path=/var/log/supervisor owner={{supervisord_user}} group={{supervisord_group}} state=directory

- name: Create /var/run/supervisor directory
  sudo: True
  file: path=/var/run/supervisor owner={{supervisord_user}} group={{supervisord_group}} state=directory

- name: Install supervisor config
  sudo: True
  template: src=supervisor.conf.j2 dest=/etc/supervisord.conf
  notify: 
   - restart supervisord

- name: Install supervisor service script
  sudo: True
  template: src=supervisord.sh.j2 dest=/etc/init.d/supervisord mode=0755

- name: Start supervisor
  sudo: True
  service: name=supervisord state=started
