apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ianlewis-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 10%
  template:
    metadata:
      labels:
        name: ianlewis-api
    spec:
      containers:
        - name: ianlewis-api
          image: asia.gcr.io/ianlewis-org/ianlewis-api:0.6.7
          livenessProbe:
            # an http probe
            httpGet:
              path: /_status/healthz
              port: 8080
          readinessProbe:
            # an http probe
            httpGet:
              path: /_status/readiness
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            limits:
              memory: 25Mi
              cpu: 10m
      volumes: 
        - name: certs
          hostPath:
            path: /etc/ssl/certs
