apiVersion: v1
kind: ReplicationController
metadata:
  name: ianlewis-api-0.1.1-0
  labels:
    name: ianlewis-api
    version: 0.1.1-0
spec:
  replicas: 1
  selector:
    name: ianlewis-api
    version: 0.1.1-0
  template:
    metadata:
      labels:
        name: ianlewis-api
        version: 0.1.1-0
    spec:
      containers:
        - name: ianlewis-api
          image: asia.gcr.io/ianlewis-org/ianlewis-api:0.1.1
          env:
            - name: API_SERVER_CRT
              value: /conf/api-server-crt
            - name: API_SERVER_KEY
              value: /conf/api-server-key
          livenessProbe:
            # an http probe
            httpGet:
              path: /healthz
              port: 9090
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: secret-volume
              mountPath: /conf
          resources:
            limits:
              memory: 25Mi
              cpu: 10m
      volumes: 
        - name: certs
          hostPath:
            path: /etc/ssl/certs
        - name: secret-volume
          secret:
            secretName: api-server-secret
