apiVersion: v1
kind: ReplicationController
metadata:
  name: ianlewis-api-0.6.5-0
  labels:
    name: ianlewis-api
    version: 0.6.5-0
spec:
  replicas: 1
  selector:
    name: ianlewis-api
    version: 0.6.5-0
  template:
    metadata:
      labels:
        name: ianlewis-api
        version: 0.6.5-0
    spec:
      containers:
        - name: ianlewis-api
          image: asia.gcr.io/ianlewis-org/ianlewis-api:0.6.5
          env:
            - name: API_SERVER_BASE_URL
              value: /api
          livenessProbe:
            # an http probe
            httpGet:
              path: /_status/healthz
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
          resources:
            limits:
              memory: 25Mi
              cpu: 10m
      volumes: 
        - name: certs
          hostPath:
            path: /etc/ssl/certs
