apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: ianlewis-api 
    version: "3"
  name: ianlewis-api-v3
spec:
  ports:
    - port: 443
      targetPort: 8080
  selector: 
    name: ianlewis-api
  type: NodePort
