apiVersion: v1
kind: Service
metadata: 
  name: ianlewis-api
  labels: 
    name: ianlewis-api 
    version: "5"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector: 
    name: ianlewis-api
  type: NodePort
