apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: ianlewis-api 
    version: "4"
  name: ianlewis-api-v4
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector: 
    name: ianlewis-api
  type: NodePort
