#!/bin/sh

# djangoのプロジェクトトップディレクトリを指定する                                                                    
BASEDIR=/var/www/vhosts/homepage
WORKDIR=$BASEDIR/app                                                                                                  
VENVDIR=/var/www/venvs/homepage

. $VENVDIR/bin/activate

APP="wsgi_app:application"
HOST=127.0.0.1
PORT=10023
PIDFILE=$BASEDIR/tmp/gunicorn.pid
LOGFILE=$BASEDIR/logs/gunicorn.log

if [ -f $PIDFILE ]; then
    rm $PIDFILE
fi

cd $BASEDIR
PYTHONPATH=$PYTHONPATH:$BASEDIR/scripts \
    exec setuidgid www-data \
    gunicorn \
    -c $BASEDIR/scripts/gunicorn.conf.py \
    --pid=$PIDFILE \
    --log-file=$LOGFILE \
    --bind=$HOST:$PORT \
    $APP
